services:
  backend:
    # ... (keep all existing configuration)
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=workflow_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - LLM_PROVIDER=ollama
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=http://localhost:5001/api/oauth/gdrive/callback
      - FASTAPI_SECRET_KEY=your_secret_key_here
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5001

# ... (rest of the docker-compose.yml content)
