global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend API - FIXED: Changed port from 5000 to 5001
  - job_name: 'workflow-backend'
    static_configs:
      - targets: ['backend:5001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Frontend - REMOVED: Frontend doesn't serve metrics, only HTML
  # - job_name: 'workflow-frontend'
  #   static_configs:
  #     - targets: ['frontend:80']
  #   metrics_path: '/metrics'
  #   scrape_interval: 30s

  # PostgreSQL - REMOVED: Raw postgres doesn't serve prometheus metrics on 5432
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['db:5432']

  # MinIO - Fixed metrics path
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 30s

  # Qdrant
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis - REMOVED: Raw redis doesn't serve prometheus metrics on 6379
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis:6379']

  # Node Exporter - REMOVED: You don't have this service in docker-compose
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093